Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.box = "debian/bookworm64"
    master.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 2048
    end
  end

  config.vm.define "worker1" do |worker|
    worker.vm.box = "debian/bookworm64"
    worker.vm.provider "virtualbox" do |v|
      v.cpus = 1 
      v.memory = 1024
    end
  end

  config.vm.define "worker2" do |worker|
    worker.vm.box = "debian/bookworm64"
    worker.vm.provider "virtualbox" do |v|
      v.cpus = 1 
      v.memory = 1024
    end
  end

end
